=== davidalvarezdlt/resumpy/cv.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "lang": {
      "type": "string",
      "enum": [
        "en",
        "es"
      ]
    },
    "last_update": {
      "type": "string",
      "pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
    },
    "basic": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "surnames": {
          "type": "string"
        },
        "profession": {
          "type": "string"
        },
        "birthday": {
          "type": "string",
          "pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
        },
        "birthplace": {
          "type": "string"
        },
        "residence": {
          "type": "string"
        },
        "marital_status": {
          "type": "string"
        },
        "biography": {
          "type": "string"
        },
        "hobbies": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "surnames",
        "profession"
      ]
    },
    "contact": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "website": {
          "type": "object",
          "properties": {
            "anchor": {
              "type": "string"
            },
            "href": {
              "type": "string"
            }
          },
          "required": [
            "anchor",
            "href"
          ]
        },
        "twitter": {
          "type": "object",
          "properties": {
            "anchor": {
              "type": "string"
            },
            "href": {
              "type": "string"
            }
          },
          "required": [
            "anchor",
            "href"
          ]
        },
        "linkedin": {
          "type": "object",
          "properties": {
            "anchor": {
              "type": "string"
            },
            "href": {
              "type": "string"
            }
          },
          "required": [
            "anchor",
            "href"
          ]
        },
        "github": {
          "type": "object",
          "properties": {
            "anchor": {
              "type": "string"
            },
            "href": {
              "type": "string"
            }
          },
          "required": [
            "anchor",
            "href"
          ]
        },
        "scholar": {
          "type": "object",
          "properties": {
            "anchor": {
              "type": "string"
            },
            "href": {
              "type": "string"
            }
          },
          "required": [
            "anchor",
            "href"
          ]
        }
      },
      "required": [
        "email",
        "phone"
      ]
    },
    "experience": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "institution": {
            "type": "string"
          },
          "position": {
            "type": "string"
          },
          "date_start": {
            "type": "string",
            "pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
          },
          "date_end": {
            "type": "string",
            "pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
          },
          "description": {
            "type": "array"
          }
        },
        "required": [
          "institution",
          "position",
          "date_start"
        ]
      },
      "uniqueItems": true
    },
    "education": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "institution": {
            "type": "string"
          },
          "degree": {
            "type": "string"
          },
          "major": {
            "type": "string"
          },
          "date_start": {
            "type": "string",
            "pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
          },
          "date_end": {
            "type": "string",
            "pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
          },
          "description": {
            "type": "array"
          },
          "gpa": {
            "type": "number",
            "minimum": 0
          },
          "gpa_max": {
            "type": "number",
            "minimum": 0
          },
          "performance": {
            "type": "number",
            "minimum": 0,
            "maximum": 100
          },
          "promotion_order": {
            "type": "string"
          }
        },
        "required": [
          "institution",
          "degree",
          "date_start"
        ]
      },
      "uniqueItems": true
    },
    "awards": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "institution": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
          },
          "description": {
            "type": "string"
          },
          "diploma": {
            "type": "object",
            "properties": {
              "anchor": {
                "type": "string"
              },
              "href": {
                "type": "string"
              }
            },
            "required": [
              "anchor",
              "href"
            ]
          }
        },
        "required": [
          "institution",
          "name",
          "date"
        ]
      },
      "uniqueItems": true
    },
    "publications": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "abstract": {
            "type": "string"
          },
          "authors": {
            "type": "string"
          },
          "conference": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
          },
          "manuscript_link": {
            "type": "object",
            "properties": {
              "anchor": {
                "type": "string"
              },
              "href": {
                "type": "string"
              }
            },
            "required": [
              "anchor",
              "href"
            ]
          },
          "code_link": {
            "type": "object",
            "properties": {
              "anchor": {
                "type": "string"
              },
              "href": {
                "type": "string"
              }
            },
            "required": [
              "anchor",
              "href"
            ]
          }
        },
        "required": [
          "title",
          "authors",
          "date"
        ]
      },
      "uniqueItems": true
    },
    "languages": {
      "type": "array",
      "items": {
        "type": "object",
        "parameters": {
          "name": {
            "type": "string"
          },
          "level": {
            "type": "string"
          },
          "diploma": {
            "type": "object",
            "properties": {
              "anchor": {
                "type": "string"
              },
              "href": {
                "type": "string"
              }
            },
            "required": [
              "anchor",
              "href"
            ]
          }
        },
        "required": [
          "name",
          "level"
        ]
      },
      "uniqueItems": true
    },
    "courses": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "institution": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "pattern": "^\\d{4}-([0]\\d|1[0-2])-([0-2]\\d|3[01])$"
          },
          "diploma": {
            "type": "object",
            "properties": {
              "anchor": {
                "type": "string"
              },
              "href": {
                "type": "string"
              }
            },
            "required": [
              "anchor",
              "href"
            ]
          }
        },
        "required": [
          "institution",
          "name",
          "date"
        ]
      },
      "uniqueItems": true
    },
    "projects": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "featured": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "link": {
            "type": "object",
            "properties": {
              "anchor": {
                "type": "string"
              },
              "href": {
                "type": "string"
              }
            },
            "required": [
              "anchor",
              "href"
            ]
          }
        },
        "required": [
          "name"
        ]
      },
      "unique": true
    },
    "skills": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "score": {
            "type": "number",
            "minimum": 0,
            "maximum": 100
          }
        },
        "required": [
          "name"
        ]
      },
      "uniqueItems": true
    }
  },
  "required": [
    "lang",
    "last_update",
    "basic",
    "contact"
  ]
}

=== davidalvarezdlt/resumpy/cv.example.json
{
  "lang": "en",
  "last_update": "2020-10-28",
  "basic": {
    "name": "David",
    "surnames": "\u00c1lvarez de la Torre",
    "profession": "Telecommunication Engineer",
    "birthday": "1996-01-20",
    "birthplace": "Barcelona",
    "residence": "Zurich",
    "marital_status": "Single",
    "biography": "Passionate about technology and engineering with a special interest in machine learning, software development, probability theory and algorithms. Currently at UBS working on applying the last advances on machine learning to solve some of the most important non-financial risk management challenges.\n With experience doing research in the machine learning field, with two published papers (one of them at ICLR). In 2019, I interned in both the VEU department of UPC and in Telefonica Research, one of the few industrial research laboratories of the country. In 2020, I had the opportunity to do my master's thesis at the Computer Vision Laboratory of ETH Z\u00fcrich.\n I studied both my bachelor's and master's in Telecommunications Engineering at the Polytechnic University of Catalonia (UPC), ranked first for engineering studies in Spain and 51-100 worldwide in the field of Electrical Engineering (QS World Ranking 2020).\n With experience releasing open-source projects. Passionate about sharing easy-to-use code and reproducible experiments. Also experienced in web development and digital marketing.",
    "hobbies": "Healthy lifestyle, travel to new places, Netflix Sundays and to learn new things."
  },
  "contact": {
    "email": "davidalvarezdlt@gmail.com",
    "phone": "(+41) 66 777 88 99",
    "website": {
      "anchor": "davidalvarezdlt.com",
      "href": "https://en.davidalvarezdlt.com/"
    },
    "twitter": {
      "anchor": "Twitter",
      "href": "https://twitter.com/DavidAlvarezDLT"
    },
    "linkedin": {
      "anchor": "LinkedIn",
      "href": "https://www.linkedin.com/in/davidalvarezdlt/"
    },
    "github": {
      "anchor": "GitHub",
      "href": "https://github.com/davidalvarezdlt"
    },
    "scholar": {
      "anchor": "Google Scholar",
      "href": "https://scholar.google.es/citations?user=WK4V8VUAAAAJ&hl=es"
    }
  },
  "experience": [
    {
      "institution": "UBS",
      "position": "Risk Modeling & Analytics Specialist",
      "date_start": "2020-09-01",
      "description": [
        {
          "type": "paragraph",
          "content": "Member of the AI Development & Platform team. Working on applying the last advances on machine learning to solve non-financial risk management challenges."
        },
        {
          "type": "paragraph",
          "content": "\n\nKey Skills: Software Development, System Administration, Machine Learning, Python, JavaScript, React.js, HTML & CSS."
        }
      ]
    },
    {
      "institution": "ETH Z\u00fcrich",
      "position": "Exchange Student",
      "date_start": "2020-02-01",
      "date_end": "2020-07-31",
      "description": [
        {
          "type": "paragraph",
          "content": "Exchange semester at the Computer Vision Laboratory of ETH Z\u00fcrich. Worked under the supervision of Sergi Caelles, Dr. Martin Danelljan, Prof. Xavier Gir\u00f3 and Prof. Luc Van Gool."
        },
        {
          "type": "itemize",
          "content": [
            "Published the master's thesis titled \"Temporal Copying and Local Hallucination for Video Inpainting\". The thesis was graded with a 5.25 / 6.00 at ETH Z\u00fcrich and with a 10.00 / 10.00 at the Polytechnic University of Catalonia."
          ]
        },
        {
          "type": "paragraph",
          "content": "Key Skills: Machine Learning, Software Development, Python, PyTorch, Numpy, Matplotlib & Research"
        }
      ]
    },
    {
      "institution": "Telefonica Research",
      "position": "Research Intern",
      "date_start": "2019-06-01",
      "date_end": "2019-11-30",
      "description": [
        {
          "type": "paragraph",
          "content": "Six-month research internship at Telefonica Research. Worked under the supervision of Dr. Joan Serr\u00e0 and Dr. Jordi Luque."
        },
        {
          "type": "itemize",
          "content": [
            "Helped with the theoretical solution and implemented both the experiments and models (Glow and PixelCNN++) used in the paper \"Input Complexity and Out-of-Distribution Detection with Likelihood-based Generative Models\", accepted at the International Conference on Learning Representations of 2020.",
            "Created a tool to generate speech data sets from YouTube videos, published in my GitHub profile."
          ]
        },
        {
          "type": "paragraph",
          "content": "Key Skills: Machine Learning, Software Development, Python, PyTorch, Numpy, Matplotlib & Research"
        }
      ]
    }
  ],
  "education": [
    {
      "institution": "Polytechnic University of Catalonia",
      "degree": "MSc. Telecommunications Engineering",
      "major": "Multimedia Intensification",
      "date_start": "2018-09-01",
      "date_end": "2020-07-31",
      "description": [
        {
          "type": "paragraph",
          "content": "Official 2-year master\u2019s program (120 ECTS) leading to the title of Telecommunication Engineer."
        },
        {
          "type": "itemize",
          "content": [
            "Coursed \"Machine Learning\", \"Computer Vision\" and \"Advanced Human Language Processing\" as intensification subjects.",
            "54.16% of the credits with a mark equal or superior to 9.00 / 10.00.",
            "Completed the master's thesis at ETH Z\u00fcrich, one of the most competitive universities of the exchange program. The thesis was graded with a 10.00 / 10.00.",
            "Implemented the technical solution of a real business challenge along with students from ESADE Business School as part of the subject \"Interdisciplinary Innovation Project\", sponsored by ARAG. The subject was graded with a 9.60 / 10.00.",
            "Published the paper \"Problem-Agnostic Speech Embeddings for Multi-Speaker Text-to-Speech with SampleRNN\" at the 10th ISCA Speech Synthesis Workshop as part of the subject \"Introduction to Research\". The subject was graded with a 10.00 / 10.00."
          ]
        }
      ],
      "gpa": 9.15,
      "gpa_max": 10.0,
      "performance": 100.0
    },
    {
      "institution": "Polytechnic University of Catalonia",
      "degree": "BSc. Telecommunications Technologies and Services Engineering",
      "major": "Audiovisual Specialization",
      "date_start": "2014-09-01",
      "date_end": "2018-07-31",
      "description": [
        {
          "type": "paragraph",
          "content": "Official 4-year bachelor\u2019s program (240 ECTS) leading to the title of Technical Telecommunication Engineer."
        },
        {
          "type": "itemize",
          "content": [
            "Coursed \"Audio and Voice Signal Processing\", \"Image and Video Signal Processing\", \"Audiovisual Coding\", \"Acoustics and Electroacoustic\", \"Audiovisual Technology and Production\" and \"Multimedia Communications\" as specialization subjects.",
            "72.50% of the credits with a mark equal or superior to 7.00 / 10.00.",
            "Published the bachelor's thesis titled \"Real-Time Stock Predictions with Deep Learning and News Scrapping\", supervised by Prof. Jos\u00e9 Adri\u00e1n Rodr\u00edguez Fonollosa. The thesis was graded with a 9.70 / 10.00.",
            "Served as the technical lead for a team of 13 people as part of the subject \"Advanced Engineering Project\", sponsored by CaixaBank. The subject was graded with a 9.50 / 10.00.",
            "Obtained the \"recognition of outstanding academic achievement\", awarded to students who have not failed any subject during the bachelor."
          ]
        }
      ],
      "gpa": 7.72,
      "gpa_max": 10.0,
      "performance": 100.0,
      "promotion_order": "22 / 373"
    }
  ],
  "awards": [
    {
      "institution": "Government of Spain",
      "name": "Collaboration Scholarship",
      "date": "2018-11-01",
      "description": "Scholarship of \u20ac2000 whose purpose is to initiate students in research tasks in the department of their choice. Granted annually to the 2000 applicants with the best GPAs of the Spanish territory."
    },
    {
      "institution": "Polytechnic University of Catalonia",
      "name": "Recognition of Outstanding Academic Achievement",
      "date": "2018-11-26",
      "description": "Granted to those students who passed all subjects in the first attempt without failing any of them. Around 10-20% of the students get this distinction in each promotion.",
      "diploma": {
        "anchor": "Recognition",
        "href": "https://davidalvarezdlt.cdn.prismic.io/davidalvarezdlt/661dd369-0264-40aa-9236-edbaeb32502b_sobre-mi-reconocimientos-excelencia.pdf"
      }
    },
    {
      "institution": "CARNET Barcelona",
      "name": "Hackathon Mobility 2018 - First Place of the SEAT Challenge",
      "date": "2018-03-11",
      "description": "The Hackathon consisted of using both the sensors of a robot and an Amazon Alexa to create a smart driving assistant. Our solution included functionalities such as face detection, face recognition, facial gesture detection, event alerts and the inclusion of an innovative optimal refuelling algorithm. The price was composed by \u20ac2000 in cash plus the opportunity to present the solution in front of high-rank managers in the headquarters of the company.",
      "diploma": {
        "anchor": "Prize",
        "href": "https://davidalvarezdlt.cdn.prismic.io/davidalvarezdlt%2F9c868325-3e7a-40a7-a961-6afaf25f67b3_sobre-mi-premios-hackmob2018.pdf"
      }
    }
  ],
  "publications": [
    {
      "title": "Temporal Copying and Local Hallucination for Video Inpainting",
